// Generated with Shader Minifier 1.3.6 (https://github.com/laurentlb/Shader_Minifier/)
#ifndef FRAG_DRAW_H_
# define FRAG_DRAW_H_
# define VAR_fragColor "r"
# define VAR_iFrame "n"
# define VAR_iResolution "S"

const char *draw_frag =
 "#version 430\n"
 "layout(location=0) out vec4 r;"
 "layout(location=0) uniform vec4 S;"
 "layout(location=1) uniform int n;\n"
 "#define NUM_MAT 4\n"
 "vec3 v[NUM_MAT]={vec3(.8),vec3(.2,.8,.2),vec3(.8,.2,.2),vec3(.2,.2,.8)};"
 "float m(vec3 v)"
 "{"
   "return length(v)-.5;"
 "}"
 "float m(vec3 v,vec3 S)"
 "{"
   "vec3 n=abs(v)-S;"
   "return min(max(n.x,max(n.y,n.z)),0.)+length(max(n,0.));"
 "}struct SDFInfo{int index;};"
 "float t(vec3 v,inout SDFInfo S)"
 "{"
   "float n;"
   "n=m(v);"
   "float r,x=m(v,vec3(17,7,17)),t=m(v,vec3(15,5,15)),i=m(v-vec3(0,5,0),vec3(5,4,5));"
   "r=max(x,-t);"
   "r=max(r,-i);"
   "S.index=0;"
   "S.index=n<r?"
     "1:"
     "S.index;"
   "n=min(n,r);"
   "float L=m(v-vec3(2,0,0)),l=m(v+vec3(2,0,0));"
   "S.index=L<n?"
     "3:"
     "S.index;"
   "n=min(n,L);"
   "S.index=l<n?"
     "2:"
     "S.index;"
   "return min(n,l);"
 "}"
 "vec3 t(vec3 v)"
 "{"
   "vec2 S=vec2(.001,0);"
   "SDFInfo n;"
   "return normalize(vec3(t(v+S.xyy,n)-t(v-S.xyy,n),t(v+S.yxy,n)-t(v-S.yxy,n),t(v+S.yyx,n)-t(v-S.yyx,n)));"
 "}struct SurfaceInfo{vec3 color;vec3 normal;vec3 position;};\n"
 "#define MAX_STEP 300\n"
 "bool m(vec3 n,vec3 S,inout SurfaceInfo r)"
 "{"
   "float m=0.,x=0.;"
   "SDFInfo i;"
   "for(int l=0;l<MAX_STEP;l++)"
     "{"
       "m=t(n+S*x,i);"
       "if(m<.001)"
         "return r.position=n+S*x,r.color=vec3(1),r.normal=t(r.position),r.color=v[i.index],true;"
       "x+=m;"
     "}"
   "r.color=vec3(0);"
   "r.normal=vec3(0);"
   "return false;"
 "}\n"
 "#define LIGHT_DIR normalize(vec3(.5,1.,0.))\n"
 "vec3 x(vec3 n)"
 "{"
   "vec3 v=vec3(0,0,-3),r=vec3(0);"
   "SurfaceInfo S;"
   "if(m(v,n,S))"
     "{"
       "vec3 x=LIGHT_DIR,l=S.position+x*.02;"
       "SurfaceInfo i;"
       "bool L=m(l,x,i);"
       "r=S.color*(max(dot(S.normal,LIGHT_DIR),0.)*(1.-float(L))+.2);"
     "}"
   "else"
     " r=vec3(0);"
   "return r;"
 "}"
 "void main()"
 "{"
   "vec2 v=(gl_FragCoord.xy*2.-S.xy)/S.y;"
   "vec3 n=vec3(0);"
   "n=x(normalize(vec3(v,1)));"
   "r=vec4(n,1);"
 "}";

#endif // FRAG_DRAW_H_
