// Generated with Shader Minifier 1.3.6 (https://github.com/laurentlb/Shader_Minifier/)
#ifndef FRAG_DRAW_H_
# define FRAG_DRAW_H_
# define VAR_fragColor "S"
# define VAR_iFrame "m"
# define VAR_iResolution "n"

const char *draw_frag =
 "#version 430\n"
 "layout(location=0) out vec4 S;"
 "layout(location=0) uniform vec4 n;"
 "layout(location=1) uniform int m;"
 "float v(vec3 v,vec3 n)"
 "{"
   "vec3 m=abs(v)-n;"
   "return min(max(m.x,max(m.y,m.z)),0.)+length(max(m,0.));"
 "}struct SDFInfo{int index;};"
 "float t(vec3 m,inout SDFInfo S)"
 "{"
   "float n;"
   "n=length(m)-.5;"
   "float l,y=v(m,vec3(17,7,17)),t=v(m,vec3(15,5,15)),i=v(m-vec3(0,5,0),vec3(5,4,5));"
   "l=max(y,-t);"
   "l=max(l,-i);"
   "S.index=0;"
   "return min(n,l);"
 "}"
 "vec3 t(vec3 m)"
 "{"
   "vec2 n=vec2(.001,0);"
   "SDFInfo v;"
   "return normalize(vec3(t(m+n.xyy,v)-t(m-n.xyy,v),t(m+n.yxy,v)-t(m-n.yxy,v),t(m+n.yyx,v)-t(m-n.yyx,v)));"
 "}struct SurfaceInfo{vec3 color;vec3 normal;vec3 position;};\n"
 "#define MAX_STEP 300\n"
 "bool t(vec3 m,vec3 n,inout SurfaceInfo v)"
 "{"
   "float l=0.,y=0.;"
   "SDFInfo S;"
   "for(int r=0;r<MAX_STEP;r++)"
     "{"
       "l=t(m+n*y,S);"
       "if(l<.001)"
         "return v.position=m+n*y,v.color=vec3(1),v.normal=t(v.position),true;"
       "y+=l;"
     "}"
   "v.color=vec3(0);"
   "v.normal=vec3(0);"
   "return false;"
 "}\n"
 "#define LIGHT_DIR normalize(vec3(.5,1.,0.))\n"
 "vec3 v(vec3 v)"
 "{"
   "vec3 m=vec3(0,0,-3),n=vec3(0);"
   "SurfaceInfo S;"
   "if(t(m,v,S))"
     "{"
       "vec3 l=LIGHT_DIR,y=S.position+l*.02;"
       "SurfaceInfo i;"
       "bool r=t(y,l,i);"
       "n=S.color*(max(dot(S.normal,LIGHT_DIR),0.)*(1.-float(r))+.2);"
     "}"
   "else"
     " n=vec3(0);"
   "return n;"
 "}"
 "void main()"
 "{"
   "vec2 m=(gl_FragCoord.xy*2.-n.xy)/n.y;"
   "vec3 l=vec3(0);"
   "l=v(normalize(vec3(m,1)));"
   "S=vec4(l,1);"
 "}";

#endif // FRAG_DRAW_H_
