// Generated with Shader Minifier 1.3.6 (https://github.com/laurentlb/Shader_Minifier/)
#ifndef FRAG_DRAW_H_
# define FRAG_DRAW_H_
# define VAR_fragColor "r"
# define VAR_iFrame "m"
# define VAR_iResolution "v"

const char *draw_frag =
 "#version 430\n"
 "layout(location=0) out vec4 r;"
 "layout(location=0) uniform vec4 v;"
 "layout(location=1) uniform int m;\n"
 "#define NUM_MAT 4\n"
 "vec3 S[NUM_MAT]={vec3(.8),vec3(.2,.8,.2),vec3(.8,.2,.2),vec3(.2,.2,.8)};"
 "uint x;"
 "uint n()"
 "{"
   "x=x*747796405u+2891336453u;"
   "uint v=x,l=(v>>(v>>28u)+4u^v)*277803737u;"
   "return(l>>22u)*l;"
 "}"
 "float t()"
 "{"
   "return n()/float(4294967295U);"
 "}"
 "float n(vec3 v)"
 "{"
   "return length(v)-.5;"
 "}"
 "float n(vec3 v,vec3 n)"
 "{"
   "vec3 x=abs(v)-n;"
   "return min(max(x.x,max(x.y,x.z)),0.)+length(max(x,0.));"
 "}struct SDFInfo{int index;};"
 "float t(vec3 v,inout SDFInfo S)"
 "{"
   "float x;"
   "x=n(v);"
   "float l,m=n(v,vec3(17,7,17)),r=n(v,vec3(15,5,15)),i=n(v-vec3(0,5,0),vec3(5,4,5));"
   "l=max(m,-r);"
   "l=max(l,-i);"
   "S.index=0;"
   "S.index=x<l?"
     "1:"
     "S.index;"
   "x=min(x,l);"
   "float u=n(v-vec3(2,0,0)),L=n(v+vec3(2,0,0));"
   "S.index=u<x?"
     "3:"
     "S.index;"
   "x=min(x,u);"
   "S.index=L<x?"
     "2:"
     "S.index;"
   "return min(x,L);"
 "}"
 "vec3 t(vec3 v)"
 "{"
   "vec2 x=vec2(.001,0);"
   "SDFInfo n;"
   "return normalize(vec3(t(v+x.xyy,n)-t(v-x.xyy,n),t(v+x.yxy,n)-t(v-x.yxy,n),t(v+x.yyx,n)-t(v-x.yyx,n)));"
 "}struct SurfaceInfo{vec3 color;vec3 normal;vec3 position;};\n"
 "#define MAX_STEP 300\n"
 "bool n(vec3 v,vec3 x,inout SurfaceInfo n)"
 "{"
   "float m=0.,l=0.;"
   "SDFInfo u;"
   "for(int r=0;r<MAX_STEP;r++)"
     "{"
       "m=t(v+x*l,u);"
       "if(m<.001)"
         "return n.position=v+x*l,n.color=vec3(1),n.normal=t(n.position),n.color=S[u.index],true;"
       "l+=m;"
     "}"
   "n.color=vec3(0);"
   "n.normal=vec3(0);"
   "return false;"
 "}\n"
 "#define LIGHT_DIR normalize(vec3(.5,1.,0.))\n"
 "vec3 e(vec3 v)"
 "{"
   "vec3 x=vec3(0,0,-3),r=vec3(0);"
   "SurfaceInfo m;"
   "if(n(x,v,m))"
     "{"
       "vec3 l=LIGHT_DIR,i=m.position+l*.02;"
       "SurfaceInfo u;"
       "bool S=n(i,l,u);"
       "r=m.color*(max(dot(m.normal,LIGHT_DIR),0.)*(1.-float(S))+.2);"
     "}"
   "else"
     " r=vec3(0);"
   "return r;"
 "}"
 "void main()"
 "{"
   "x=uint((m+1)*(gl_FragCoord.x+v.x*gl_FragCoord.y));"
   "vec2 l=((gl_FragCoord.xy+vec2(t(),t()))*2.-v.xy)/v.y;"
   "vec3 S=vec3(0);"
   "S=e(normalize(vec3(l,1)));"
   "r=vec4(S,1);"
 "}";

#endif // FRAG_DRAW_H_
